# Use the base image from the devcontainer.json
FROM mcr.microsoft.com/devcontainers/base:jammy

# Install additional packages
RUN apt-get update && apt-get install -y build-essential texinfo file bison
