name: 'main verification'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to build'
        required: true
        default: '//:image_temporary_rootfs'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v5
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - run: .devcontainer/post_create.sh
      - run: scripts/version-check.sh
      - name: Check bigpicture for changes
        run: |
          scripts/bigpicture.sh
          if [[ $(git diff --stat doc) != '' ]]; then
            echo "Error: Changes in 'doc' directory. Update the documentation by running 'scripts/bigpicture.sh' and commit the changes."
            exit 1
          fi
      - name: Build
        run: |
          target=${{ github.event.inputs.target || '//:image_temporary_rootfs' }}
          bazel build --keep_going -j 1 "$target"
